<a href="https://colab.research.google.com/github/seeedata/OUTTA-AI-BOOTCAMP/blob/main/0725%20RecommendationSystem_Practice%26HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

import warnings
warnings.filterwarnings(action='ignore')

# CBF (content based filtering)

## 영화 데이터 불러오기

In [ ]:
movie=pd.read_csv("/content/drive/MyDrive/colab_data/movie_0725.csv")
movie.head()

,adult,genres,id,original_language,title
0,False,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,en,Toy Story
1,False,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,en,Jumanji
2,False,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,en,Grumpier Old Men
3,False,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,en,Waiting to Exhale
4,False,"[{'id': 35, 'name': 'Comedy'}]",11862,en,Father of the Bride Part II

In [ ]:
movie.shape

(8875, 5)

## genres 컬럼 장르 정보만 남기기

In [ ]:
movie['genres'][0]  #첫번째 영화의 장르 열

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [ ]:
#데이터 타입을 보면 문자열로 되어있음
type(movie['genres'][0])

str

In [ ]:
#문자열이 아닌 리스트 형태로 다시 바꿔주는 작업
from ast import literal_eval

movie["genres"] = movie['genres'].apply(literal_eval)

print(movie['genres'][0])
print(type(movie['genres'][0]))

[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]
<class 'list'>

In [ ]:
#장르값만 남기는 함수
def get_genres(x):
    try:
        genre = [i['name'] for i in x]
        return genre
    except:
        genre = []
        return genre

In [ ]:
movie["genres"] = movie['genres'].apply(get_genres)
movie.head()

,adult,genres,id,original_language,title
0,False,"[Animation, Comedy, Family]",862,en,Toy Story
1,False,"[Adventure, Fantasy, Family]",8844,en,Jumanji
2,False,"[Romance, Comedy]",15602,en,Grumpier Old Men
3,False,"[Comedy, Drama, Romance]",31357,en,Waiting to Exhale
4,False,[Comedy],11862,en,Father of the Bride Part II

## 장르 공백 제거하기

In [ ]:
movie['genres'][21:30]

21                              [Drama, Thriller]
22           [Action, Adventure, Crime, Thriller]
23    [Drama, Fantasy, Science Fiction, Thriller]
24                               [Drama, Romance]
25                                        [Drama]
26                        [Comedy, Drama, Family]
27                               [Drama, Romance]
28          [Fantasy, Science Fiction, Adventure]
29                                 [Drama, Crime]
Name: genres, dtype: object

In [ ]:
### 문자 공백 없애기
movie["genres"] = movie["genres"].apply(lambda x: [str(i).replace(" ","") for i in x])
movie['genres'][21:30]

21                             [Drama, Thriller]
22          [Action, Adventure, Crime, Thriller]
23    [Drama, Fantasy, ScienceFiction, Thriller]
24                              [Drama, Romance]
25                                       [Drama]
26                       [Comedy, Drama, Family]
27                              [Drama, Romance]
28          [Fantasy, ScienceFiction, Adventure]
29                                [Drama, Crime]
Name: genres, dtype: object

## 리스트에서 텍스트만 추출

In [ ]:
def get_text(x):
    return ' '.join(x)

movie['genres'] = movie['genres'].apply(get_text)
movie.head()

,adult,genres,id,original_language,title
0,False,Animation Comedy Family,862,en,Toy Story
1,False,Adventure Fantasy Family,8844,en,Jumanji
2,False,Romance Comedy,15602,en,Grumpier Old Men
3,False,Comedy Drama Romance,31357,en,Waiting to Exhale
4,False,Comedy,11862,en,Father of the Bride Part II

## 장르 TF-IDF 계산

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

tfidf_matrix = tfidf.fit_transform(movie['genres']).toarray()
tfidf_matrix

array([[0.        , 0.        , 0.72387097, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.52947876, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

## 코사인 유사도 계산

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

cos_matrix = cosine_similarity(tfidf_matrix, tfidf_matrix)
cos_matrix

array([[1.        , 0.34861102, 0.21362182, ..., 0.35100189, 0.        ,
        0.26805428],
       [0.34861102, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.21362182, 0.        , 1.        , ..., 0.6086059 , 0.        ,
        0.46478216],
       ...,
       [0.35100189, 0.        , 0.6086059 , ..., 1.        , 0.        ,
        0.76368329],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.26805428, 0.        , 0.46478216, ..., 0.76368329, 0.        ,
        1.        ]])

In [ ]:
cos_matrix.shape

(8875, 8875)

In [ ]:
df_cosine = pd.DataFrame(data=cos_matrix, index=movie['id'], columns=movie['id'])
df_cosine

id,862,8844,15602,31357,11862,949,11860,45325,9091,710,...,399106,368620,401387,314420,390989,159550,402672,97995,391698,265189
id,,,,,,,,,,,,,,,,,,,,,
862,1.000000,0.348611,0.213622,0.189955,0.351002,0.000000,0.213622,0.362279,0.000000,0.000000,...,0.936375,0.000000,0.0,0.000000,0.136336,0.000000,0.000000,0.351002,0.0,0.268054
8844,0.348611,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.649309,0.337934,0.337934,...,0.372299,0.000000,0.0,0.000000,0.000000,0.000000,0.263262,0.000000,0.0,0.000000
15602,0.213622,0.000000,1.000000,0.889212,0.608606,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.236395,0.000000,0.336923,0.608606,0.0,0.464782
31357,0.189955,0.000000,0.889212,1.000000,0.541180,0.153224,0.889212,0.139394,0.000000,0.000000,...,0.000000,0.000000,0.0,0.254105,0.210206,0.457495,0.425556,0.541180,0.0,0.708644
11862,0.351002,0.000000,0.608606,0.541180,1.000000,0.000000,0.608606,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.388421,0.000000,0.000000,1.000000,0.0,0.763683
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159550,0.000000,0.000000,0.000000,0.457495,0.000000,0.334921,0.000000,0.304690,0.000000,0.000000,...,0.000000,0.000000,0.0,0.555428,0.000000,1.000000,0.275326,0.000000,0.0,0.645591
402672,0.000000,0.263262,0.336923,0.425556,0.000000,0.092212,0.336923,0.357473,0.317339,0.317339,...,0.000000,0.000000,0.0,0.152923,0.000000,0.275326,1.000000,0.000000,0.0,0.177748
97995,0.351002,0.000000,0.608606,0.541180,1.000000,0.000000,0.608606,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.388421,0.000000,0.000000,1.000000,0.0,0.763683
391698,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.704743,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.000000
265189,0.268054,0.000000,0.464782,0.708644,0.763683,0.216222,0.464782,0.196705,0.000000,0.000000,...,0.000000,0.000000,0.0,0.358579,0.296630,0.645591,0.177748,0.763683,0.0,1.000000

## 평점 데이터 불러오기

In [ ]:
rating = pd.read_csv("/content/drive/MyDrive/colab_data/rating_0725.csv")
rating

       userId  rating     id
0           1     2.5   9909
1           1     3.0  11360
2           1     3.0    819
3           1     2.0   1103
4           1     4.0  11216
...       ...     ...    ...
99842     671     4.5  25461
99843     671     4.0  51927
99844     671     2.5    604
99845     671     2.5   1088
99846     671     4.0   4464

[99847 rows x 3 columns]

In [ ]:
#평점데이터를 8:2로 train test 데이터로 나우기

from sklearn.model_selection import train_test_split

train_rate, test_rate = train_test_split(rating, test_size=0.2, random_state=100)

In [ ]:
train_rate

       userId  rating     id
91215     606     4.5  10315
81219     553     4.0  36557
41536     299     4.5   1103
17858     119     4.0    105
76547     530     3.0  17832
...       ...     ...    ...
65615     468     2.5   1587
77655     537     5.0  12709
79683     547     4.0  64945
56088     405     4.5    120
38408     282     4.0   9800

[79877 rows x 3 columns]

# CBF 평점 공식
### user ID 5가 영화 i에 남길 예상 평점


$$ \hat{r}_{5,i}  =  \frac{\sum_{j\in I_5}{sim(i,j)}\cdot r_{5,j}}{\sum_{j\in I_5}{sim(i,j)}} $$

* $\hat{r}_{5,i}$ 사용자 5가 영화 i에 남길 평점
* $r_{5,j}$ 사용자 5가 영화 j에 남긴 평점
* $sim(i,j)$ 영화 i와 j의 유사도
* $I_5$ 사용자 5가 평점을 남긴 영화 전체 집합

In [ ]:
#train 데이터에서 유저아이디가 5인 데이터 추출
user5_train = train_rate[train_rate['userId'] == 5][['id', 'rating']]
user5_train

       id  rating
376   639     4.0
392  8916     4.0
373   510     3.0
423  1430     3.5
396   817     4.0
..    ...     ...
415  8835     4.5
404  1213     3.5
377   621     5.0
422  4147     4.0
429    12     4.0

[79 rows x 2 columns]

In [ ]:
### 공식의 분모 유사도 합 구하기 (user5_train의 79개 영화인 j와 전체 영화 i 에 대해)
sim_sum = df_cosine.loc[user5_train['id'].values, :].sum().values    #유사도 합
sim_sum = sim_sum + 1                                                #분모가 0인경우 발생할 계산오류를 피하기 위해 +1 해줌
sim_sum

array([18.03566517, 12.00646275, 32.29388642, ..., 26.83057516,
        4.33571418, 32.39231754])

In [ ]:
#공식의 분자 계산  각각 곱하고 더한 값이 필요하므로 내적 함수사용
sim_rating = np.matmul(df_cosine.loc[user5_train['id'].values, :].T.values, user5_train['rating'].values)
sim_rating

array([ 67.35395135,  42.83755096, 126.84272225, ..., 103.06395446,
        14.06628734, 124.02959458])

In [ ]:
df_cosine.loc[user5_train['id'].values, :].T.values.shape

(8875, 79)

In [ ]:
user5_train['rating'].values.shape

(79,)

In [ ]:
#최종 평점 예측
pred_rating = pd.DataFrame(np.divide(sim_rating, sim_sum), index=df_cosine.index)
pred_rating.columns=["pred"]
pred_rating

            pred
id
862     3.734487
8844    3.567874
15602   3.927763
31357   3.906486
11862   3.841288
...          ...
159550  3.681214
402672  3.772871
97995   3.841288
391698  3.244284
265189  3.828982

[8875 rows x 1 columns]

## 예측한 평점 성능평가

In [ ]:
user5_test = test_rate[test_rate['userId'] == 5][['id', 'rating']]
user5_test

        id  rating
436    558     4.5
428    310     4.0
374    240     2.5
417    161     3.0
425    672     3.0
375  37247     4.0
411   8358     3.5
414    824     3.5
412   1493     4.5
388   9552     3.5
390  10144     5.0
400  11353     3.5
435   1777     3.5
363    771     4.0
357     13     4.0
448    496     4.5
381  37165     4.0
419   4547     3.5
432    508     4.0
393   9487     3.5
355  10510     4.5

In [ ]:
user5 = pd.merge(user5_test, pred_rating.loc[user5_test['id']], left_on = 'id', right_index=True)
user5

        id  rating      pred
436    558     4.5  3.491039
428    310     4.0  3.739688
374    240     2.5  3.446859
417    161     3.0  3.045749
425    672     3.0  3.567874
375  37247     4.0  3.681214
411   8358     3.5  3.593259
414    824     3.5  3.880451
412   1493     4.5  3.646256
388   9552     3.5  3.494681
390  10144     5.0  3.501033
400  11353     3.5  3.841288
435   1777     3.5  0.000000
363    771     4.0  3.794167
357     13     4.0  3.906486
448    496     4.5  3.841288
381  37165     4.0  3.828982
419   4547     3.5  3.420763
432    508     4.0  3.906486
393   9487     3.5  3.722011
355  10510     4.5  3.661120

In [ ]:
### 평점을 잘 예측했는지 성능 평가 함수

def evaluation(pred, rating):
    rmse = np.round(math.sqrt(np.mean((pred-rating)**2)), 3)
    mae = np.mean(np.abs(pred-rating)).round(3)

    print('RMSE:', rmse)
    print('MAE:', mae)

evaluation(user5['rating'], user5['pred'])

RMSE: 0.956
MAE: 0.58

## 유사한 영화를 알려주는 함수 만들기

In [ ]:
### 어떤 영화 제목을 입력하면 그와 유사도가 높은 10개 영화와 각 예상 평점 나오도록 하는 함수 만들기
indices = pd.Series(movie.index , index=movie['title'])
indices

title
Toy Story                                                0
Jumanji                                                  1
Grumpier Old Men                                         2
Waiting to Exhale                                        3
Father of the Bride Part II                              4
                                                      ...
The Last Brickmaker in America                        8870
Mohenjo Daro                                          8871
Seven Years Bad Luck                                  8872
The Beatles: Eight Days a Week - The Touring Years    8873
Force Majeure                                         8874
Length: 8875, dtype: int64

In [ ]:
indices["Toy Story"]

0

In [ ]:
idx = indices['Toy Story']
idx

0

In [ ]:
cos_sim = list(enumerate(cos_matrix[0])); cos_sim

[(0, 1.0000000000000002),
 (1, 0.3486110188954961),
 (2, 0.21362182283676734),
 (3, 0.18995517970589537),
 (4, 0.3510018900876634),
 (5, 0.0),
 (6, 0.21362182283676734),
 (7, 0.362279495338633),
 (8, 0.0),
 (9, 0.0),
 (10, 0.18995517970589537),
 (11, 0.180954879842392),
 (12, 0.8127081615731256),
 (13, 0.0),
 (14, 0.0),
 (15, 0.0),
 (16, 0.0),
 (17, 0.19423853263243637),
 (18, 0.14837675518607882),
 (19, 0.1561250126138619),
 (20, 0.15909740022739943),
 (21, 0.0),
 (22, 0.0),
 (23, 0.0),
 (24, 0.0),
 (25, 0.0),
 (26, 0.6338048681321358),
 (27, 0.0),
 (28, 0.0),
 (29, 0.0),
 (30, 0.0),
 (31, 0.48880546613425535),
 (32, 0.0),
 (33, 0.0),
 (34, 0.30885454106688304),
 (35, 0.5749580710749944),
 (36, 0.18995517970589537),
 (37, 0.0),
 (38, 0.0),
 (39, 0.0),
 (40, 0.0),
 (41, 0.0),
 (42, 0.1383615351946294),
 (43, 0.0),
 (44, 0.0),
 (45, 0.7836104582443207),
 (46, 0.0),
 (47, 0.0),
 (48, 0.21362182283676734),
 (49, 0.0),
 (50, 0.4799738586599483),
 (51, 0.0),
 (52, 0.18995517970589537),
 (53, 0.18995517970589537),
 (54, 0.0),
 (55, 0.3486110188954961),
 (56, 0.0),
 (57, 0.36369829559519795),
 (58, 0.3510018900876634),
 (59, 0.21362182283676734),
 (60, 0.3510018900876634),
 (61, 0.0),
 (62, 0.21362182283676734),
 (63, 0.3510018900876634),
 (64, 0.0),
 (65, 0.0),
 (66, 0.18995517970589537),
 (67, 0.0),
 (68, 0.0),
 (69, 0.0),
 (70, 0.0),
 (71, 0.0),
 (72, 0.0),
 (73, 0.5313633754587492),
 (74, 0.2680542765859855),
 (75, 0.0),
 (76, 0.0),
 (77, 0.0),
 (78, 0.0),
 (79, 0.544893690689414),
 (80, 0.3510018900876634),
 (81, 0.0),
 (82, 0.0),
 (83, 0.1501834329997857),
 (84, 0.18995517970589537),
 (85, 0.0),
 (86, 0.3510018900876634),
 (87, 0.0),
 (88, 0.0),
 (89, 0.0),
 (90, 0.0),
 (91, 0.17593847193536433),
 (92, 0.21362182283676734),
 (93, 0.0),
 (94, 0.3510018900876634),
 (95, 0.0),
 (96, 0.39078854040899413),
 (97, 0.0),
 (98, 0.0),
 (99, 0.0),
 (100, 0.13604812360383767),
 (101, 0.0),
 (102, 0.0),
 (103, 0.0),
 (104, 0.17593847193536433),
 (105, 0.21362182283676734),
 (106, 0.2680542765859855),
 (107, 0.0),
 (108, 0.21362182283676734),
 (109, 0.18995517970589537),
 (110, 0.0),
 (111, 0.21362182283676734),
 (112, 0.0),
 (113, 0.21362182283676734),
 (114, 0.2680542765859855),
 (115, 0.0),
 (116, 0.0),
 (117, 0.3510018900876634),
 (118, 0.3510018900876634),
 (119, 0.0),
 (120, 0.3510018900876634),
 (121, 0.18995517970589537),
 (122, 0.13604812360383767),
 (123, 0.362279495338633),
 (124, 0.0),
 (125, 0.18995517970589537),
 (126, 0.1485644096194737),
 (127, 0.0),
 (128, 0.0),
 (129, 0.0),
 (130, 0.0),
 (131, 0.0),
 (132, 0.0),
 (133, 0.3510018900876634),
 (134, 0.2101784336328465),
 (135, 0.513209463255394),
 (136, 0.0),
 (137, 0.0),
 (138, 0.0),
 (139, 0.0),
 (140, 0.0),
 (141, 0.0),
 (142, 0.0),
 (143, 0.14613549422747849),
 (144, 0.0),
 (145, 0.0),
 (146, 0.0),
 (147, 0.0),
 (148, 0.18995517970589537),
 (149, 0.0),
 (150, 0.0),
 (151, 0.2680542765859855),
 (152, 0.0),
 (153, 0.2680542765859855),
 (154, 0.0),
 (155, 0.2680542765859855),
 (156, 0.4375140964362014),
 (157, 0.21362182283676734),
 (158, 0.27912132199478823),
 (159, 0.0),
 (160, 0.0),
 (161, 0.0),
 (162, 0.3510018900876634),
 (163, 0.3510018900876634),
 (164, 0.0),
 (165, 0.15964986515606505),
 (166, 0.0),
 (167, 0.0),
 (168, 0.0),
 (169, 0.2680542765859855),
 (170, 0.3510018900876634),
 (171, 0.0),
 (172, 0.0),
 (173, 0.0),
 (174, 0.0),
 (175, 0.0),
 (176, 0.0),
 (177, 0.3510018900876634),
 (178, 0.0),
 (179, 0.6338048681321358),
 (180, 0.0),
 (181, 0.0),
 (182, 0.0),
 (183, 0.0),
 (184, 0.0),
 (185, 0.0),
 (186, 0.0),
 (187, 0.0),
 (188, 0.3510018900876634),
 (189, 0.0),
 (190, 0.2680542765859855),
 (191, 0.5313633754587492),
 (192, 0.0),
 (193, 0.4375140964362014),
 (194, 0.3510018900876634),
 (195, 0.18995517970589537),
 (196, 0.0),
 (197, 0.0),
 (198, 0.1389132377023393),
 (199, 0.0),
 (200, 0.0),
 (201, 0.3510018900876634),
 (202, 0.18995517970589537),
 (203, 0.0),
 (204, 0.13696882490585918),
 (205, 0.13877754516816282),
 (206, 0.21362182283676734),
 (207, 0.18995517970589537),
 (208, 0.362279495338633),
 (209, 0.8174355891946693),
 (210, 0.0),
 (211, 0.3883982593650092),
 (212, 0.0),
 (213, 0.3883982593650092),
 (214, 0.6901280038276834),
 (215, 0.0),
 (216, 0.0),
 (217, 0.0),
 (218, 0.689935370477022),
 (219, 0.0),
 (220, 0.6338048681321358),
 (221, 0.0),
 (222, 0.18995517970589537),
 (223, 0.0),
 (224, 0.0),
 (225, 0.19423853263243637),
 (226, 0.5749580710749944),
 (227, 0.0),
 (228, 0.38859822616508416),
 (229, 0.0),
 (230, 0.0),
 (231, 0.0),
 (232, 0.3883982593650092),
 (233, 0.0),
 (234, 0.0),
 (235, 0.0),
 (236, 0.0),
 (237, 0.544893690689414),
 (238, 0.0),
 (239, 0.0),
 (240, 0.0),
 (241, 0.0),
 (242, 0.13877754516816282),
 (243, 0.0),
 (244, 0.5704042191942651),
 (245, 0.18995517970589537),
 (246, 0.21362182283676734),
 (247, 0.3883982593650092),
 (248, 0.21362182283676734),
 (249, 0.2680542765859855),
 (250, 0.0),
 (251, 0.2680542765859855),
 (252, 0.0),
 (253, 0.0),
 (254, 0.0),
 (255, 0.0),
 (256, 0.0),
 (257, 0.18995517970589537),
 (258, 0.0),
 (259, 0.0),
 (260, 0.0),
 (261, 0.0),
 (262, 0.18995517970589537),
 (263, 0.18995517970589537),
 (264, 0.0),
 (265, 0.0),
 (266, 0.0),
 (267, 0.0),
 (268, 0.0),
 (269, 0.0),
 (270, 0.2680542765859855),
 (271, 0.0),
 (272, 0.0),
 (273, 0.15575378133100465),
 (274, 0.0),
 (275, 0.2680542765859855),
 (276, 0.7238709723180883),
 (277, 0.3883982593650092),
 (278, 0.0),
 (279, 0.0),
 (280, 0.48880546613425535),
 (281, 0.0),
 (282, 0.0),
 (283, 0.0),
 (284, 0.2680542765859855),
 (285, 0.19423853263243637),
 (286, 0.18995517970589537),
 (287, 0.3510018900876634),
 (288, 0.0),
 (289, 0.11849979699637678),
 (290, 0.15154782942550205),
 (291, 0.0),
 (292, 0.0),
 (293, 0.0),
 (294, 0.0),
 (295, 0.3510018900876634),
 (296, 0.0),
 (297, 0.0),
 (298, 0.0),
 (299, 0.0),
 (300, 0.0),
 (301, 0.18995517970589537),
 (302, 0.0),
 (303, 0.21362182283676734),
 (304, 0.18995517970589537),
 (305, 0.6338048681321358),
 (306, 0.1680236848013109),
 (307, 0.2680542765859855),
 (308, 0.0),
 (309, 0.0),
 (310, 0.16750831083490367),
 (311, 0.0),
 (312, 0.0),
 (313, 0.541245542409334),
 (314, 0.2680542765859855),
 (315, 0.0),
 (316, 0.0),
 (317, 0.513209463255394),
 (318, 0.18995517970589537),
 (319, 0.18995517970589537),
 (320, 0.0),
 (321, 0.1656713227536861),
 (322, 0.18995517970589537),
 (323, 0.41349976617584505),
 (324, 0.0),
 (325, 0.8926290461248766),
 (326, 0.0),
 (327, 0.0),
 (328, 0.12344884246474523),
 (329, 0.10093366939054453),
 (330, 0.0),
 (331, 0.19423853263243637),
 (332, 0.2680542765859855),
 (333, 0.0),
 (334, 0.0),
 (335, 0.0),
 (336, 0.0),
 (337, 0.0),
 (338, 0.21362182283676734),
 (339, 0.0),
 (340, 0.0),
 (341, 0.0),
 (342, 0.0),
 (343, 0.0),
 (344, 0.0),
 (345, 0.1561250126138619),
 (346, 0.0),
 (347, 0.0),
 (348, 0.0),
 (349, 0.0),
 (350, 0.5595139112366552),
 (351, 0.0),
 (352, 0.0),
 (353, 0.0),
 (354, 0.0),
 (355, 0.0),
 (356, 0.0),
 (357, 0.513209463255394),
 (358, 0.0),
 (359, 0.1296884918944159),
 (360, 0.689935370477022),
 (361, 0.2101784336328465),
 (362, 0.10093366939054453),
 (363, 0.18995517970589537),
 (364, 0.15964986515606505),
 (365, 0.3510018900876634),
 (366, 0.1561250126138619),
 (367, 0.362279495338633),
 (368, 0.0),
 (369, 0.0),
 (370, 0.0),
 (371, 0.0),
 (372, 0.0),
 (373, 0.0),
 (374, 0.0),
 (375, 0.3510018900876634),
 (376, 0.0),
 (377, 0.11233730949478883),
 (378, 0.14370613144526906),
 (379, 0.0),
 (380, 0.5227831465494203),
 (381, 0.0),
 (382, 0.5704042191942651),
 (383, 0.11668936134154674),
 (384, 0.0),
 (385, 0.3510018900876634),
 (386, 0.2680542765859855),
 (387, 0.0),
 (388, 0.0),
 (389, 0.11285397560571268),
 (390, 0.3510018900876634),
 (391, 0.0),
 (392, 0.18995517970589537),
 (393, 0.0),
 (394, 0.3510018900876634),
 (395, 0.2680542765859855),
 (396, 0.0),
 (397, 0.09010466318987599),
 (398, 0.21362182283676734),
 (399, 0.0),
 (400, 0.4410285352678241),
 (401, 0.0),
 (402, 0.0),
 (403, 0.0),
 (404, 0.0),
 (405, 0.547781817680796),
 (406, 0.0),
 (407, 0.0),
 (408, 0.0),
 (409, 0.0),
 (410, 0.12447983866515722),
 (411, 0.3510018900876634),
 (412, 0.18995517970589537),
 (413, 0.0),
 (414, 0.3510018900876634),
 (415, 0.2680542765859855),
 (416, 0.2680542765859855),
 (417, 0.3510018900876634),
 (418, 0.0),
 (419, 0.0),
 (420, 0.18995517970589537),
 (421, 0.0),
 (422, 0.0),
 (423, 0.0),
 (424, 0.0),
 (425, 0.0),
 (426, 0.0),
 (427, 0.362279495338633),
 (428, 0.40700554835913305),
 (429, 0.689935370477022),
 (430, 0.11668936134154674),
 (431, 0.0),
 (432, 0.3510018900876634),
 (433, 0.0),
 (434, 0.0),
 (435, 0.1680236848013109),
 (436, 0.0),
 (437, 0.0),
 (438, 0.0),
 (439, 0.15671787048074196),
 (440, 0.18995517970589537),
 (441, 0.0),
 (442, 0.21362182283676734),
 (443, 0.6338048681321358),
 (444, 0.2680542765859855),
 (445, 0.0),
 (446, 0.0),
 (447, 0.41726572019025),
 (448, 0.0),
 (449, 0.0),
 (450, 0.0),
 (451, 0.0),
 (452, 0.0),
 (453, 0.0),
 (454, 0.0),
 (455, 0.09696521304155666),
 (456, 0.3510018900876634),
 (457, 0.0),
 (458, 0.14139948808354005),
 (459, 0.0),
 (460, 0.21362182283676734),
 (461, 0.0),
 (462, 0.3510018900876634),
 (463, 0.0),
 (464, 0.0),
 (465, 0.0),
 (466, 0.0),
 (467, 0.0),
 (468, 0.0),
 (469, 0.2680542765859855),
 (470, 0.0),
 (471, 0.3883982593650092),
 (472, 0.1270723194207106),
 (473, 0.0),
 (474, 0.0),
 (475, 0.2680542765859855),
 (476, 0.5313633754587492),
 (477, 0.2680542765859855),
 (478, 0.15575378133100465),
 (479, 0.18995517970589537),
 (480, 0.0),
 (481, 0.0),
 (482, 0.18995517970589537),
 (483, 0.15752093622315824),
 (484, 0.0),
 (485, 0.44437950539427135),
 (486, 0.0),
 (487, 0.0),
 (488, 0.0),
 (489, 0.541245542409334),
 (490, 0.7807802095869983),
 (491, 0.1551285099356659),
 (492, 0.0),
 (493, 0.0),
 (494, 0.0),
 (495, 0.0),
 (496, 0.6901280038276834),
 (497, 0.2680542765859855),
 (498, 0.0),
 (499, 0.2680542765859855),
 (500, 0.0),
 (501, 0.21362182283676734),
 (502, 0.0),
 (503, 0.2680542765859855),
 (504, 0.2680542765859855),
 (505, 0.689935370477022),
 (506, 0.09341488544113373),
 (507, 0.12032699992914539),
 (508, 0.2680542765859855),
 (509, 0.5749580710749944),
 (510, 0.41349976617584505),
 (511, 0.11234725498446438),
 (512, 0.0),
 (513, 0.3510018900876634),
 (514, 0.689935370477022),
 (515, 0.0),
 (516, 0.7291632583148038),
 (517, 0.0),
 (518, 0.0),
 (519, 0.0),
 (520, 0.0),
 (521, 0.7807802095869983),
 (522, 0.6245893109751762),
 (523, 0.9363747503830332),
 (524, 0.21362182283676734),
 (525, 0.0),
 (526, 0.0),
 (527, 0.21362182283676734),
 (528, 0.21362182283676734),
 (529, 0.0),
 (530, 0.0),
 (531, 0.5159434126340626),
 (532, 0.5595139112366552),
 (533, 0.0),
 (534, 0.21362182283676734),
 (535, 0.0),
 (536, 0.0),
 (537, 0.12032699992914539),
 (538, 0.8814287105654255),
 (539, 0.0),
 (540, 0.689935370477022),
 (541, 0.0),
 (542, 0.0),
 (543, 0.13696882490585918),
 (544, 0.1485644096194737),
 (545, 0.0),
 (546, 0.0),
 (547, 0.6613562539602075),
 (548, 0.0),
 (549, 0.3510018900876634),
 (550, 0.2680542765859855),
 (551, 0.689935370477022),
 (552, 0.18995517970589537),
 (553, 0.3510018900876634),
 (554, 0.0),
 (555, 0.0),
 (556, 0.0),
 (557, 0.0),
 (558, 0.3510018900876634),
 (559, 0.0),
 (560, 0.2101784336328465),
 (561, 0.0),
 (562, 0.8127081615731256),
 (563, 0.0),
 (564, 0.3510018900876634),
 (565, 0.17593847193536433),
 (566, 0.13385067328233635),
 (567, 0.0),
 (568, 0.0),
 (569, 0.17852407466741904),
 (570, 0.8241349958200991),
 (571, 0.0),
 (572, 0.0),
 (573, 0.0),
 (574, 0.0),
 (575, 0.0),
 (576, 0.0),
 (577, 0.0),
 (578, 0.4799738586599483),
 (579, 0.0),
 (580, 0.18995517970589537),
 (581, 0.0),
 (582, 0.0),
 (583, 0.0),
 (584, 0.0),
 (585, 0.15534300278143195),
 (586, 0.0),
 (587, 0.541245542409334),
 (588, 0.0),
 (589, 0.0),
 (590, 0.0),
 (591, 0.21362182283676734),
 (592, 0.0),
 (593, 0.21362182283676734),
 (594, 1.0000000000000002),
 (595, 0.3510018900876634),
 (596, 0.4410285352678241),
 (597, 0.0),
 (598, 0.0),
 (599, 0.13281093103746097),
 (600, 0.13281093103746097),
 (601, 0.0),
 (602, 0.0),
 (603, 0.2680542765859855),
 (604, 0.0),
 (605, 0.18995517970589537),
 (606, 0.0),
 (607, 0.0),
 (608, 0.12735328252530032),
 (609, 0.0),
 (610, 0.0),
 (611, 0.5001838856886913),
 (612, 0.0),
 (613, 0.2101784336328465),
 (614, 1.0000000000000002),
 (615, 0.0),
 (616, 0.689935370477022),
 (617, 0.0),
 (618, 0.13385067328233635),
 (619, 0.18995517970589537),
 (620, 0.0),
 (621, 0.4410285352678241),
 (622, 0.0),
 (623, 0.0),
 (624, 0.0),
 (625, 0.0),
 (626, 0.0),
 (627, 0.0),
 (628, 0.0),
 (629, 0.16400674011828414),
 (630, 0.0),
 (631, 0.6338048681321358),
 (632, 0.0),
 (633, 0.0),
 (634, 0.21362182283676734),
 (635, 0.0),
 (636, 0.0),
 (637, 0.0),
 (638, 0.8926290461248766),
 (639, 0.1927387760546042),
 (640, 0.3510018900876634),
 (641, 0.0),
 (642, 0.0),
 (643, 0.11910671378897734),
 (644, 0.0),
 (645, 0.0),
 (646, 0.180954879842392),
 (647, 0.0),
 (648, 0.6338048681321358),
 (649, 0.0),
 (650, 0.18995517970589537),
 (651, 0.21362182283676734),
 (652, 0.0),
 (653, 0.0),
 (654, 0.0),
 (655, 0.16750831083490367),
 (656, 0.43213989023365323),
 (657, 0.689935370477022),
 (658, 0.0),
 (659, 0.3510018900876634),
 (660, 0.0),
 (661, 0.0),
 (662, 0.7807802095869983),
 (663, 0.12273442390242463),
 (664, 0.3510018900876634),
 (665, 0.18995517970589537),
 (666, 0.0),
 (667, 0.3510018900876634),
 (668, 0.3510018900876634),
 (669, 0.0),
 (670, 0.0),
 (671, 0.513209463255394),
 (672, 0.18995517970589537),
 (673, 0.0),
 (674, 0.689935370477022),
 (675, 0.0),
 (676, 0.180954879842392),
 (677, 0.0),
 (678, 0.0),
 (679, 0.0),
 (680, 0.2680542765859855),
 (681, 0.0),
 (682, 0.0),
 (683, 0.0),
 (684, 0.18995517970589537),
 (685, 0.0),
 (686, 0.0),
 (687, 0.0),
 (688, 0.0),
 (689, 0.689935370477022),
 (690, 0.0),
 (691, 0.689935370477022),
 (692, 0.0),
 (693, 0.0),
 (694, 0.0),
 (695, 0.0),
 (696, 0.0),
 (697, 0.689935370477022),
 (698, 0.0),
 (699, 0.513209463255394),
 (700, 0.1353872192930698),
 (701, 0.8127081615731256),
 (702, 0.0),
 (703, 0.0),
 (704, 0.18995517970589537),
 (705, 0.0),
 (706, 0.0),
 (707, 0.0),
 (708, 0.21362182283676734),
 (709, 0.13500642843705146),
 (710, 0.1283898960999785),
 (711, 0.13500642843705146),
 (712, 0.18995517970589537),
 (713, 0.0),
 (714, 0.0),
 (715, 0.21362182283676734),
 (716, 0.0),
 (717, 0.13500642843705146),
 (718, 0.0),
 (719, 0.18995517970589537),
 (720, 0.21362182283676734),
 (721, 0.12677604947167473),
 (722, 0.0),
 (723, 0.0),
 (724, 0.3289342511819856),
 (725, 0.18995517970589537),
 (726, 0.21362182283676734),
 (727, 0.6338048681321358),
 (728, 0.13500642843705146),
 (729, 0.3486110188954961),
 (730, 0.0),
 (731, 0.2680542765859855),
 (732, 0.0),
 (733, 0.0),
 (734, 0.0),
 (735, 0.0),
 (736, 0.2680542765859855),
 (737, 0.0),
 (738, 0.0),
 (739, 0.0),
 (740, 0.0),
 (741, 0.0),
 (742, 0.0),
 (743, 0.541245542409334),
 (744, 0.15604471765288738),
 (745, 0.21362182283676734),
 (746, 0.18995517970589537),
 (747, 0.13500642843705146),
 (748, 0.21362182283676734),
 (749, 0.0),
 (750, 0.0),
 (751, 0.0),
 (752, 0.0),
 (753, 0.0),
 (754, 0.13500642843705146),
 (755, 0.14139948808354005),
 (756, 0.21362182283676734),
 (757, 0.0),
 (758, 0.0),
 (759, 0.13632380588813897),
 (760, 0.2680542765859855),
 (761, 0.40865022758305286),
 (762, 0.3883982593650092),
 (763, 0.2680542765859855),
 (764, 0.21362182283676734),
 (765, 0.0),
 (766, 0.0),
 (767, 0.14550925106960372),
 (768, 0.5313633754587492),
 (769, 0.0),
 (770, 0.13500642843705146),
 (771, 0.0),
 (772, 0.0),
 (773, 0.0),
 (774, 0.0),
 (775, 0.0),
 (776, 0.11212629226903782),
 (777, 0.0),
 (778, 0.0),
 (779, 0.18995517970589537),
 (780, 0.0),
 (781, 0.0),
 (782, 0.0),
 (783, 0.0),
 (784, 0.18995517970589537),
 (785, 0.362279495338633),
 (786, 0.0),
 (787, 0.14606964063563257),
 (788, 0.0),
 (789, 0.0),
 (790, 0.0),
 (791, 0.0),
 (792, 0.0),
 (793, 0.0),
 (794, 0.0),
 (795, 0.19423853263243637),
 (796, 0.0),
 (797, 0.0),
 (798, 0.5374415500661809),
 (799, 0.0),
 (800, 0.689935370477022),
 (801, 0.27621471565391764),
 (802, 0.30062652060841183),
 (803, 0.513209463255394),
 (804, 0.4602404226140379),
 (805, 0.0),
 (806, 0.689935370477022),
 (807, 0.0),
 (808, 0.5159434126340626),
 (809, 0.689935370477022),
 (810, 0.4410285352678241),
 (811, 0.6338048681321358),
 (812, 0.0),
 (813, 0.3510018900876634),
 (814, 0.48880546613425535),
 (815, 0.7230495194798593),
 (816, 0.747204177748167),
 (817, 0.747204177748167),
 (818, 0.9363747503830332),
 (819, 0.8926290461248766),
 (820, 0.0),
 (821, 0.513209463255394),
 (822, 0.9363747503830332),
 (823, 0.8499401110928931),
 (824, 0.6785978035630698),
 (825, 0.7046666463947866),
 (826, 0.7836104582443207),
 (827, 0.1927387760546042),
 (828, 0.3289342511819856),
 (829, 0.0),
 (830, 0.0),
 (831, 0.0),
 (832, 0.0),
 (833, 0.2680542765859855),
 (834, 0.0),
 (835, 0.0),
 (836, 0.18995517970589537),
 (837, 0.0),
 (838, 0.0),
 (839, 0.0),
 (840, 0.2680542765859855),
 (841, 0.0),
 (842, 0.0),
 (843, 0.0),
 (844, 0.0),
 (845, 0.13500642843705146),
 (846, 0.0),
 (847, 0.21362182283676734),
 (848, 0.0),
 (849, 0.0),
 (850, 0.8127081615731256),
 (851, 0.13500642843705146),
 (852, 0.13500642843705146),
 (853, 0.0),
 (854, 0.0),
 (855, 0.4109412806443681),
 (856, 0.0),
 (857, 0.14878504827153477),
 (858, 0.3510018900876634),
 (859, 0.19423853263243637),
 (860, 0.3510018900876634),
 (861, 0.13500642843705146),
 (862, 0.2680542765859855),
 (863, 0.19232955273683516),
 (864, 0.0),
 (865, 0.0),
 (866, 0.0),
 (867, 0.0),
 (868, 0.0),
 (869, 0.0),
 (870, 0.0),
 (871, 0.3510018900876634),
 (872, 0.0),
 (873, 0.0),
 (874, 0.0),
 (875, 0.0),
 (876, 0.0),
 (877, 0.30062652060841183),
 (878, 0.3883982593650092),
 (879, 0.0),
 (880, 0.0),
 (881, 0.0),
 (882, 0.0),
 (883, 0.0),
 (884, 0.0),
 (885, 0.3510018900876634),
 (886, 0.3510018900876634),
 (887, 0.0),
 (888, 0.0),
 (889, 0.0),
 (890, 0.0),
 (891, 0.13632380588813897),
 (892, 0.513209463255394),
 (893, 0.0),
 (894, 0.0),
 (895, 0.0),
 (896, 0.0),
 (897, 0.0),
 (898, 0.0),
 (899, 0.3510018900876634),
 (900, 0.13820991057947718),
 (901, 0.0),
 (902, 0.0),
 (903, 0.0),
 (904, 1.0000000000000002),
 (905, 0.0),
 (906, 0.5249578823166335),
 (907, 0.0),
 (908, 0.0),
 (909, 0.0),
 (910, 0.0),
 (911, 0.2680542765859855),
 (912, 0.2680542765859855),
 (913, 0.2680542765859855),
 (914, 0.0),
 (915, 0.3510018900876634),
 (916, 0.0),
 (917, 0.0),
 (918, 0.2680542765859855),
 (919, 0.0),
 (920, 0.0),
 (921, 0.3510018900876634),
 (922, 0.13281093103746097),
 (923, 0.0),
 (924, 0.0),
 (925, 0.0),
 (926, 0.0),
 (927, 0.12032699992914539),
 (928, 0.0),
 (929, 0.0),
 (930, 0.1251839144161916),
 (931, 0.0),
 (932, 0.0),
 (933, 0.0),
 (934, 0.18995517970589537),
 (935, 0.0),
 (936, 0.14727834204189266),
 (937, 0.0),
 (938, 0.0),
 (939, 0.0),
 (940, 0.3510018900876634),
 (941, 0.0),
 (942, 0.40865022758305286),
 (943, 0.0),
 (944, 0.17852407466741904),
 (945, 0.0),
 (946, 0.0),
 (947, 0.2680542765859855),
 (948, 0.0),
 (949, 0.0),
 (950, 0.0),
 (951, 0.0),
 (952, 0.0),
 (953, 0.0),
 (954, 0.0),
 (955, 0.0),
 (956, 0.0),
 (957, 0.0),
 (958, 0.0),
 (959, 0.1338026860898836),
 (960, 0.0),
 (961, 0.0),
 (962, 0.0),
 (963, 0.11626593020809613),
 (964, 0.0),
 (965, 0.0),
 (966, 0.7808218408278841),
 (967, 0.0),
 (968, 0.0),
 (969, 0.18995517970589537),
 (970, 0.0),
 (971, 0.0),
 (972, 0.18995517970589537),
 (973, 0.0),
 (974, 0.0),
 (975, 0.0),
 (976, 0.17593847193536433),
 (977, 0.18995517970589537),
 (978, 0.2680542765859855),
 (979, 0.0),
 (980, 0.2680542765859855),
 (981, 0.0),
 (982, 0.180954879842392),
 (983, 0.0),
 (984, 0.2680542765859855),
 (985, 0.18995517970589537),
 (986, 0.0),
 (987, 0.0),
 (988, 0.0),
 (989, 0.0),
 (990, 0.0),
 (991, 0.0),
 (992, 0.0),
 (993, 0.0),
 (994, 0.0),
 (995, 0.1209836978705661),
 (996, 0.3510018900876634),
 (997, 0.3510018900876634),
 (998, 0.0),
 (999, 0.0),
 ...]

In [ ]:
cos_sim.sort(key=lambda x: x[1], reverse=True)

In [ ]:
cos_sim = cos_sim[0:11]
cos_sim

[(0, 1.0000000000000002),
 (594, 1.0000000000000002),
 (614, 1.0000000000000002),
 (904, 1.0000000000000002),
 (1396, 1.0000000000000002),
 (1588, 1.0000000000000002),
 (2033, 1.0000000000000002),
 (2472, 1.0000000000000002),
 (2698, 1.0000000000000002),
 (2962, 1.0000000000000002),
 (3756, 1.0000000000000002)]

In [ ]:
sim_movie_idx = [x[0] for x in cos_sim]; sim_movie_idx

[0, 594, 614, 904, 1396, 1588, 2033, 2472, 2698, 2962, 3756]

In [ ]:
if idx in sim_movie_idx:
    sim_movie_idx.remove(idx)

In [ ]:
def similar_movie_1(title, cos_matrix):
    idx = indices[title]                #제목을 입력하면 해당 인덱스 값(몇번째 행인지)을 가져옴

    cos_sim = list(enumerate(cos_matrix[idx]))        #몇번째 행인지와 유사도를 같이 가져옴

    cos_sim.sort(key = lambda x : x[1], reverse=True)   #유사도 값을 기준으로 내림차순 정렬

    cos_sim = cos_sim[0:11]                          #상위 11개 작품 (다음 코드에서 입력한 작품 제외할 것)
    sim_movie_idx=[x[0] for x in cos_sim]            #cos_sim에서 첫번째 항목만 즉, 몇행인지 값 추출

    if idx in sim_movie_idx:                         #해당 작품 제외
        sim_movie_idx.remove(idx)

    sim_movie_idx = sim_movie_idx[0:10]              #상위 10개 작품만

    title_list = movie['title'].iloc[sim_movie_idx]  #인덱스로 유사한 영화 제목 추출
    title_list = pd.DataFrame(title_list)            #데이터프레임 만듦

    id_list = movie['id'].iloc[sim_movie_idx]        #인덱스로 영화 id 추출
    id_list = pd.DataFrame(id_list)                  #데이터 프레임으로 만듦

    temp1 = pd.concat([title_list, id_list], axis=1)                              #title_list, id_list 데이터프레임 병합

    temp2 = pd.merge(temp1, pred_rating["pred"], left_on='id', right_index=True)   #temp1과 pred_rating 병합

    result = temp2.drop(["id"], axis=1)
    result.rename(columns={"title": "유사한 영화 TOP10", "pred": "예상평점"}, inplace=True)

    print(result)

In [ ]:
indices["The City of Lost Children"]

28

In [ ]:
similar_movie_1("The City of Lost Children", cos_matrix)

                          유사한 영화 TOP10      예상평점
5977                A Trip to the Moon  3.429416
6713       Hellboy II: The Golden Army  3.429416
6721                            Jumper  3.429416
7756                  The Hunger Games  3.429416
3354                    The Lost World  3.580827
5166  Frank Herbert's Children of Dune  3.580827
1259                Kull the Conqueror  3.492034
2089                          Superman  3.492034
2090                       Superman II  3.492034
3059                         Supergirl  3.492034

In [ ]:
indices['Sabrina']

title
Sabrina      6
Sabrina    725
dtype: int64

In [ ]:
similar_movie_1("Sabrina", cos_matrix)   #영화제목은 같으나 영화id가 다른 경우 에러 발생

ValueError: ignored

In [ ]:
#영화 제목은 같은데 영화 id는 다를경우 위 함수로는 에러가 남. 영화 id가 다르면 다른 영화로 보고 모두 출력하는 함수 만들기

def similar_movie(title, cos_matrix):

    try:
        idx = indices[title]                #제목을 입력하면 해당 인덱스 값(몇번째 행인지)을 가져옴

        cos_sim = list(enumerate(cos_matrix[idx]))         #몇번째 행인지와 유사도를 같이 가져옴
        cos_sim.sort(key=lambda x :x[1], reverse=True)    #유사도 값을 기준으로 내림차순 정렬

        cos_sim = cos_sim[0:11]                           #상위 11개 작품 (다음 코드에서 입력한 작품 제외할 것)
        sim_movie_idx = [x[0] for x in cos_sim]            #cos_sim에서 첫번쨰 항목만 즉, 몇행인지 값 추출
        sim_movie_idx.remove(idx)                        #해당 작품 제외
        sim_movie_idx = sim_movie_idx[0:10]              #상위 10개 작품만

        title_list = movie['title'].iloc[sim_movie_idx]  #인덱스로 유사한 영화 제목 추출
        title_list = pd.DataFrame(title_list)           #데이터프레임 만듦

        id_list = movie['id'].iloc[sim_movie_idx]     #인덱스로 영화 id 추출
        id_list = pd.DataFrame(id_list)  #데이터 프레임으로 만듦

        temp1 = pd.concat([title_list, id_list], axis=1)   #title_list, id_list 데이터프레임 병합
        temp2 = pd.merge(temp1, pred_rating["pred"], left_on = 'id', right_index=True)    #temp1과 pred_rating 병합

        result=temp2.drop(["id"], axis=1)
        result.rename(columns={"title":"유사한 영화 TOP10", "pred":"예상평점"}, inplace=True)

        print(result)

    except:
        idx=[]

        if len(indices[title]) > 1:

            for i in range(len(indices[title])):
                idx.append(indices[title][i])                          #같은 제목중 코드 하나만

                cos_sim = list(enumerate(cos_matrix[idx[i]]))         #몇번째 행인지와 유사도를 같이 가져옴
                cos_sim.sort(key=lambda x :x[1], reverse=True)    #유사도 값을 기준으로 내림차순 정렬

                cos_sim = cos_sim[0:11]                         #상위 11개 작품 (다음 코드에서 입력한 작품 제외할 것)
                sim_movie_idx = [x[0] for x in cos_sim]            #cos_sim에서 첫번쨰 항목만 즉, 몇행인지 값 추출

                if idx[i] in sim_movie_idx:
                    sim_movie_idx.remove(idx[i])                    #해당 작품 제외

                sim_movie_idx = sim_movie_idx[0:10]              #상위 10개 작품만

                title_list = movie['title'].iloc[sim_movie_idx]  #인덱스로 유사한 영화 제목 추출
                title_list = pd.DataFrame(title_list)

                id_list = movie['id'].iloc[sim_movie_idx]     #인덱스로 영화 id 추출
                id_list = pd.DataFrame(id_list)

                temp1 = pd.concat([title_list, id_list], axis=1)

                temp2 = pd.merge(temp1, pred_rating["pred"], left_on = 'id', right_index=True)    #temp1과 pred_rating 병합

                result = temp2.drop(["id"], axis=1)
                result.rename(columns={"title":f"영화 id:{idx[i]} 유사한 영화 TOP10", "pred":"예상평점"}, inplace=True)

                print(result)

In [ ]:
similar_movie("Sabrina", cos_matrix)

       영화 id:6 유사한 영화 TOP10      예상평점
2          Grumpier Old Men  3.927763
48         Mighty Aphrodite  3.927763
59            Two If by Sea  3.927763
62             French Twist  3.927763
92                Mr. Wrong  3.927763
105            If Lucy Fell  3.927763
108               Boomerang  3.927763
111  Flirting with Disaster  3.927763
113          Pie in the Sky  3.927763
157                Mallrats  3.927763
       영화 id:725 유사한 영화 TOP10      예상평점
3           Waiting to Exhale  3.906486
10     The American President  3.906486
36                   Clueless  3.906486
52      Home for the Holidays  3.906486
53                The Postman  3.906486
66      Kicking and Screaming  3.906486
84            Beautiful Girls  3.906486
109         Chungking Express  3.906486
121     The Brothers McMullen  3.906486
125  An Awfully Big Adventure  3.906486

In [ ]:
similar_movie("Alice in Wonderland", cos_matrix)

                             영화 id:825 유사한 영화 TOP10      예상평점
1629                                   The Rescuers  3.574249
2217         Little Nemo: Adventures In Slumberland  3.574249
3901                           Return to Never Land  3.574249
4167                                  Spirited Away  3.574249
5522                              The Polar Express  3.574249
5769                      Kirikou and the Sorceress  3.574249
6444                      Arthur and the Invisibles  3.574249
7316                       How to Train Your Dragon  3.574249
7439  Legend of the Guardians: The Owls of Ga'Hoole  3.574249
8117                                           Epic  3.574249
                       영화 id:7293 유사한 영화 TOP10      예상평점
1                                      Jumanji  3.567874
55                  The Indian in the Cupboard  3.567874
729                           The Wizard of Oz  3.567874
1508                                 Labyrinth  3.567874
1632                              Return to Oz  3.567874
3763  Harry Potter and the Philosopher's Stone  3.567874
4130                       Clash of the Titans  3.567874
4258   Harry Potter and the Chamber of Secrets  3.567874
4460        Journey to the Center of the Earth  3.567874
4951                                 Peter Pan  3.567874
                      영화 id:7444 유사한 영화 TOP10      예상평점
158   Mighty Morphin Power Rangers: The Movie  3.591250
2677          Baby: Secret of the Lost Legend  3.591250
3005          Sinbad and the Eye of the Tiger  3.591250
2708         Teenage Mutant Ninja Turtles III  3.726441
1187             Turbo: A Power Rangers Movie  3.570395
7106                   Race to Witch Mountain  3.570395
802                  Escape to Witch Mountain  3.559942
877                E.T. the Extra-Terrestrial  3.559942
1583       Darby O'Gill and the Little People  3.559942
1630               Return from Witch Mountain  3.559942

# User based CF (collaborative filtering)

In [ ]:
#평점데이터와 영화데이터의 id, title 병합하기
df= pd.merge(rating, movie[["id","title"]], on="id")
df

       userId  rating      id                          title
0           1     2.5    9909                Dangerous Minds
1           7     3.0    9909                Dangerous Minds
2          31     4.0    9909                Dangerous Minds
3          32     4.0    9909                Dangerous Minds
4          36     3.0    9909                Dangerous Minds
...       ...     ...     ...                            ...
98550     664     3.0   34812  H.G. Wells' War of the Worlds
98551     664     4.5   22825                        The Box
98552     665     4.0  110972                 Pie in the Sky
98553     665     3.0   26602                   Summer Catch
98554     668     3.0   36807                  The Sixth Man

[98555 rows x 4 columns]

In [ ]:
#각 유저가 영화에 남긴 평점들로 이루어진 데이터 프레임 만들기
df3 = df.copy().pivot_table("rating", index="userId", columns="id")
df3.fillna(0, inplace=True)
df3

id,2,5,6,11,12,13,14,15,16,18,...,376570,384798,387893,390989,391698,399106,401387,402672,410921,416437
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,3.0,5.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,5.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
668,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
669,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
670,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
671,0.0,0.0,0.0,4.0,0.0,5.0,3.5,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## user-based cf 유사도 계산

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

cos_matrix_3 = cosine_similarity(df3.values, df3.values)
cos_matrix_3

array([[1.        , 0.        , 0.        , ..., 0.0480577 , 0.        ,
        0.02367533],
       [0.        , 1.        , 0.12682458, ..., 0.02478699, 0.19422398,
        0.09883407],
       [0.        , 0.12682458, 1.        , ..., 0.08253112, 0.12760636,
        0.17510851],
       ...,
       [0.0480577 , 0.02478699, 0.08253112, ..., 1.        , 0.05424404,
        0.05384711],
       [0.        , 0.19422398, 0.12760636, ..., 0.05424404, 1.        ,
        0.1614514 ],
       [0.02367533, 0.09883407, 0.17510851, ..., 0.05384711, 0.1614514 ,
        1.        ]])

In [ ]:
cos_matrix_3.shape

(671, 671)

In [ ]:
df3_cosine= pd.DataFrame(data=cos_matrix_3, index=df3.index, columns=df3.index)
df3_cosine

userId,1,2,3,4,5,6,7,8,9,10,...,662,663,664,665,666,667,668,669,670,671
userId,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.000000,0.000000,0.074714,0.016818,0.000000,0.084825,0.000000,0.012843,0.000000,...,0.000000,0.000000,0.018850,0.048426,0.000000,0.000000,0.000000,0.048058,0.000000,0.023675
2,0.000000,1.000000,0.126825,0.120170,0.104498,0.000000,0.197844,0.114630,0.114265,0.043568,...,0.448826,0.020123,0.073289,0.161596,0.444087,0.481427,0.005611,0.024787,0.194224,0.098834
3,0.000000,0.126825,1.000000,0.082879,0.153354,0.061421,0.158332,0.253912,0.136093,0.116052,...,0.149219,0.024364,0.160037,0.115863,0.180214,0.177542,0.000000,0.082531,0.127606,0.175109
4,0.074714,0.120170,0.082879,1.000000,0.131055,0.079896,0.324338,0.192461,0.030512,0.137612,...,0.106947,0.016478,0.138503,0.244845,0.093511,0.090381,0.073517,0.095145,0.067317,0.215614
5,0.016818,0.104498,0.153354,0.131055,1.000000,0.063796,0.096964,0.166451,0.086616,0.032370,...,0.201964,0.000000,0.157836,0.185140,0.141644,0.058810,0.044216,0.039065,0.084830,0.221317
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,0.000000,0.481427,0.177542,0.090381,0.058810,0.000000,0.256565,0.095494,0.102470,0.057056,...,0.410318,0.034160,0.077470,0.154941,0.344634,1.000000,0.019051,0.034715,0.193229,0.130597
668,0.000000,0.005611,0.000000,0.073517,0.044216,0.025189,0.026237,0.039900,0.137311,0.083474,...,0.000000,0.000000,0.060893,0.052358,0.000000,0.019051,1.000000,0.000000,0.068219,0.094058
669,0.048058,0.024787,0.082531,0.095145,0.039065,0.041728,0.068092,0.047863,0.044747,0.059797,...,0.033136,0.015104,0.058473,0.102318,0.019535,0.034715,0.000000,1.000000,0.054244,0.053847
670,0.000000,0.194224,0.127606,0.067317,0.084830,0.028388,0.130945,0.197141,0.326163,0.138931,...,0.175331,0.085627,0.098305,0.108001,0.154261,0.193229,0.068219,0.054244,1.000000,0.161451
671,0.023675,0.098834,0.175109,0.215614,0.221317,0.086339,0.252657,0.364637,0.123081,0.165704,...,0.091597,0.017362,0.199529,0.218150,0.118496,0.130597,0.094058,0.053847,0.161451,1.000000

In [ ]:
df3.head(3)

id,2,5,6,11,12,13,14,15,16,18,...,376570,384798,387893,390989,391698,399106,401387,402672,410921,416437
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,3.0,5.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# user-based CF 평점 공식
$$ \hat{r}_{5,i}  = \bar{r_5}+ \frac{\sum_{v\in U_i}(r_{v,i}- \bar{r_v})\cdot{sim(5,v)} }{\sum_{v\in U_i}{sim(5,v)}} $$

* $\hat{r}_{5,i}$ 사용자 5가 영화 i에 남길 평점
* $\bar{r_5}$ 사용자 5가 영화에 남긴 평점들의 평균
* $sim(5,v)$ 사용자 5와 v의 유사도
* $U_i$ 영화 i에 대해 평점을 남긴 사용자 전체 집합

In [ ]:
#df3에 대해 0과 1로 이루어진 데이터프레임 만들기
bin_df = df3.copy()
bin_df[bin_df==0.0] = 0.0
bin_df[bin_df!=0.0] = 1.0
bin_df

id,2,5,6,11,12,13,14,15,16,18,...,376570,384798,387893,390989,391698,399106,401387,402672,410921,416437
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
668,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
669,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
670,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
671,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
#유저가 평점을 남긴 영화의 개수 (즉, bin_df에서 1의 개수)
bin_sum= bin_df.sum(axis=1)
bin_sum

userId
1       20.0
2       75.0
3       50.0
4      203.0
5      100.0
       ...
667     67.0
668     18.0
669     36.0
670     29.0
671    111.0
Length: 671, dtype: float64

In [ ]:
#유저별 남긴 평점 평균 구하기
#평균 구하기
rating_average = pd.DataFrame(df3.sum(axis=1).divide(bin_sum))
rating_average.columns = ['average']
rating_average.head()

         average
userId
1       2.550000
2       3.480000
3       3.560000
4       4.344828
5       3.910000

### user based CF 평점 공식 분자 구하기
$$\sum_{v\in U_i}(r_{v,i}- \bar{r_v})\cdot{sim(5,v)}$$

In [ ]:
#유저 아이디 5와 다른 유저들의 유사도 => sim(5,v)
sim_user5 = df3_cosine.loc[5, :]
sim_user5

userId
1      0.016818
2      0.104498
3      0.153354
4      0.131055
5      1.000000
         ...
667    0.058810
668    0.044216
669    0.039065
670    0.084830
671    0.221317
Name: 5, Length: 671, dtype: float64

In [ ]:
sim_user5[5] = 0 #유저 5자신 값 0으로 바꿈

In [ ]:
#최종 sim(5,v)
sim_user5

userId
1      0.016818
2      0.104498
3      0.153354
4      0.131055
5      0.000000
         ...
667    0.058810
668    0.044216
669    0.039065
670    0.084830
671    0.221317
Name: 5, Length: 671, dtype: float64

In [ ]:
print(df3.shape)
print(rating_average.shape)
print(bin_df.shape)

(671, 8834)
(671, 1)
(671, 8834)

In [ ]:
#bin_df 활용 크기 맞추기
bin_df.T.multiply(rating_average['average']).T

id,2,5,6,11,12,13,14,15,16,18,...,376570,384798,387893,390989,391698,399106,401387,402672,410921,416437
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.000000,0.00,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.000000,0.00,3.480000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.000000,3.56,3.560000,3.560000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,4.344828,0.00,4.344828,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.000000,3.91,3.910000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,0.0,0.0,0.0,0.000000,0.00,3.641791,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
668,0.0,0.0,0.0,3.833333,0.00,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
669,0.0,0.0,0.0,0.000000,0.00,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
670,0.0,0.0,0.0,0.000000,0.00,0.000000,3.775862,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
671,0.0,0.0,0.0,3.923423,0.00,3.923423,3.923423,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
sim_user5

userId
1      0.016818
2      0.104498
3      0.153354
4      0.131055
5      0.000000
         ...
667    0.058810
668    0.044216
669    0.039065
670    0.084830
671    0.221317
Name: 5, Length: 671, dtype: float64

In [ ]:
(df3 - bin_df.T.multiply(rating_average['average']).T).T.multiply(sim_user5).T

id,2,5,6,11,12,13,14,15,16,18,...,376570,384798,387893,390989,391698,399106,401387,402672,410921,416437
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.000000,0.000000,-0.050159,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.000000,-0.085878,0.220830,0.067476,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.085864,0.000000,0.085864,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,0.0,0.0,0.0,0.000000,0.000000,0.079877,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
668,0.0,0.0,0.0,-0.036847,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
669,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
670,0.0,0.0,0.0,0.000000,0.000000,0.000000,-0.150646,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
671,0.0,0.0,0.0,0.016948,0.000000,0.238265,-0.093711,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
#유사한 유저들을 곱해 공식 분자 식 완성
user_simrating = (df3 - bin_df.T.multiply(rating_average['average']).T).T.multiply(sim_user5).T.sum(axis=0)

In [ ]:
user_simrating     #영화별로 값이 나옴

id
2          0.013414
5          0.040713
6         -0.077773
11        11.898586
12         2.022910
            ...
399106     0.087097
401387    -0.400894
402672     0.057055
410921    -0.121685
416437     0.102452
Length: 8834, dtype: float64

### user based CF 평점 공식 분모 계산
$$\sum_{v\in U_i}{sim(5,v)}$$

In [ ]:
#유사도의 합
sim_sum = bin_df.T.multiply(sim_user5).T.sum(axis=0)

In [ ]:
sim_sum     #이 값도 영화별로 나옴  최종적으로 구하는 것이 영화별 평점 예측이니까

id
2          0.023691
5          3.111457
6          0.586714
11        34.680364
12        21.804937
            ...
399106     0.137344
401387     0.189209
402672     0.064925
410921     0.169107
416437     0.097541
Length: 8834, dtype: float64

### user based CF 평점 공식 최종 계산
$$ \hat{r}_{5,i}  = \bar{r_5}+ \frac{\sum_{v\in U_i}(r_{v,i}- \bar{r_v})\cdot{sim(5,v)} }{\sum_{v\in U_i}{sim(5,v)}} $$

In [ ]:
#최종 평점 예측 값
pred_rating = rating_average.loc[5].values + pd.Series(data = np.divide(user_simrating, sim_sum), name='pred')
pred_rating.fillna(0, inplace=True)
pred_rating

id
2         4.476225
5         3.923085
6         3.777443
11        4.253093
12        4.002773
            ...
399106    4.544152
401387    1.791209
402672    4.788788
410921    3.190421
416437    4.960347
Name: pred, Length: 8834, dtype: float64

## user based CF 성능평가

In [ ]:
user5_test = test_rate[test_rate['userId'] == 5][['id', 'rating']]
user5_test

        id  rating
436    558     4.5
428    310     4.0
374    240     2.5
417    161     3.0
425    672     3.0
375  37247     4.0
411   8358     3.5
414    824     3.5
412   1493     4.5
388   9552     3.5
390  10144     5.0
400  11353     3.5
435   1777     3.5
363    771     4.0
357     13     4.0
448    496     4.5
381  37165     4.0
419   4547     3.5
432    508     4.0
393   9487     3.5
355  10510     4.5

In [ ]:
user_temp =pd.merge(user5_test, pred_rating.loc[user5_test['id']], left_on = 'id', right_index=True)
user_temp

        id  rating      pred
436    558     4.5  4.014069
428    310     4.0  3.583973
374    240     2.5  4.594790
417    161     3.0  4.074043
425    672     3.0  3.830929
375  37247     4.0  4.265914
411   8358     3.5  3.867502
414    824     3.5  4.110406
412   1493     4.5  3.445898
388   9552     3.5  3.946920
390  10144     5.0  3.953840
400  11353     3.5  3.539168
435   1777     3.5  4.165712
363    771     4.0  3.639294
357     13     4.0  4.238293
448    496     4.5  3.751394
381  37165     4.0  4.110529
419   4547     3.5  3.620788
432    508     4.0  4.008368
393   9487     3.5  3.894902
355  10510     4.5  3.710290

In [ ]:
# 오차 확인
evaluation(user_temp['pred'], user_temp['rating'])

RMSE: 0.744
MAE: 0.58

# 💻 과제   Item-based CF (collaborative filtering)

In [ ]:
df= pd.merge(rating, movie[["id","title"]], on="id")
df

       userId  rating      id                          title
0           1     2.5    9909                Dangerous Minds
1           7     3.0    9909                Dangerous Minds
2          31     4.0    9909                Dangerous Minds
3          32     4.0    9909                Dangerous Minds
4          36     3.0    9909                Dangerous Minds
...       ...     ...     ...                            ...
98550     664     3.0   34812  H.G. Wells' War of the Worlds
98551     664     4.5   22825                        The Box
98552     665     4.0  110972                 Pie in the Sky
98553     665     3.0   26602                   Summer Catch
98554     668     3.0   36807                  The Sixth Man

[98555 rows x 4 columns]

### 1. 위의 df를 사용하여 item-based cf에 필요한 평점으로 이루어진 데이터 df2 를 만드세요.  (결측값은 0으로) <font color=blue>(10점)</font>

In [ ]:
df2 = df.copy().pivot_table("rating", index="id", columns="userId")
df2.fillna(0, inplace=True)
df2

userId,1,2,3,4,5,6,7,8,9,10,...,662,663,664,665,666,667,668,669,670,671
id,,,,,,,,,,,,,,,,,,,,,
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,5.0,0.0,0.0,5.0,3.5,0.0,0.0,...,0.0,0.0,4.0,3.0,0.0,0.0,3.0,0.0,0.0,4.0
12,0.0,0.0,3.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399106,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
401387,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
402672,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
410921,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
416437,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### 2. df2의 데이터를 사용하여 코사인 유사도 cos_matrix_2 를 구하여 데이터 프레임 df2_cosine을 만드세요.<font color=blue>(10점)</font><br>(인덱스, 컬럼 모두 df2의 인덱스로)

In [ ]:
cos_matrix_2 = cosine_similarity(df2.values, df2.values)
cos_matrix_2

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 0.03860457,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.03860457, 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [ ]:
df2_cosine = pd.DataFrame(data=cos_matrix_2, index=df2.index, columns=df2.index)
df2_cosine

id,2,5,6,11,12,13,14,15,16,18,...,376570,384798,387893,390989,391698,399106,401387,402672,410921,416437
id,,,,,,,,,,,,,,,,,,,,,
2,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.226779,0.000000,...,0.000000,0.00000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0
5,0.0,1.000000,0.000000,0.197563,0.099554,0.150947,0.098432,0.079485,0.055027,0.169195,...,0.000000,0.00000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.038605,0.0
6,0.0,0.000000,1.000000,0.087767,0.000000,0.122642,0.074557,0.100317,0.000000,0.087997,...,0.000000,0.00000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0
11,0.0,0.197563,0.087767,1.000000,0.399134,0.547707,0.465270,0.349091,0.169882,0.477609,...,0.064620,0.05744,0.0,0.043080,0.0,0.0,0.071800,0.0,0.040616,0.0
12,0.0,0.099554,0.000000,0.399134,1.000000,0.442042,0.371946,0.199155,0.153964,0.345131,...,0.095659,0.00000,0.0,0.035872,0.0,0.0,0.023915,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399106,0.0,0.000000,0.000000,0.000000,0.000000,0.040461,0.048401,0.129413,0.000000,0.000000,...,0.000000,0.00000,0.0,0.000000,1.0,1.0,0.000000,0.0,0.000000,0.0
401387,0.0,0.000000,0.000000,0.071800,0.023915,0.013487,0.064535,0.129413,0.100791,0.024596,...,0.000000,0.00000,0.0,0.000000,0.0,0.0,1.000000,0.0,0.000000,0.0
402672,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.0,0.000000,0.0,0.0,0.000000,1.0,0.000000,0.0
410921,0.0,0.038605,0.000000,0.040616,0.000000,0.047684,0.045633,0.164715,0.000000,0.034784,...,0.000000,0.00000,0.0,0.000000,0.0,0.0,0.000000,0.0,1.000000,0.0
416437,0.0,0.000000,0.000000,0.000000,0.000000,0.053948,0.048401,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,1.0

## 3.item-based CF 평점 공식을 이용하여 예측 평점을 계산하세요
$$ \hat{r}_{5,i}  =  \frac{\sum_{j\in I_5}{sim(i,j)}\cdot r_{5,j}}{\sum_{j\in I_5}{sim(i,j)}} $$

* $\hat{r}_{5,i}$ 사용자 5가 영화 i에 남길 평점
* $r_{5,j}$ 사용자 5가 영화 j에 남긴 평점
* $sim(i,j)$ 영화 i와 j의 유사도
* $I_5$ 사용자 5가 평점을 남긴 영화 전체 집합

### 3-(1) train_rate에서 유저 5의 데이터를 user5_train으로 만들어주세요.<font color=blue>(5점)</font>

In [ ]:
user5_train = train_rate[train_rate['userId'] == 5]
user5_train

     userId  rating    id
376       5     4.0   639
392       5     4.0  8916
373       5     3.0   510
423       5     3.5  1430
396       5     4.0   817
..      ...     ...   ...
415       5     4.5  8835
404       5     3.5  1213
377       5     5.0   621
422       5     4.0  4147
429       5     4.0    12

[79 rows x 3 columns]

### 3-(2) 공식의 분모인 유사도 합을 구하세요. <font color=blue>(20점)</font>

In [ ]:
sim_sum = df2_cosine.loc[user5_train['id'].values, :].sum().values    #유사도 합
sim_sum = sim_sum + 1                                                #분모가 0인경우 발생할 계산오류를 피하기 위해 +1 해줌
sim_sum

array([ 1.38829044, 10.91533732,  6.65166546, ...,  1.30397893,
        4.53056159,  2.42612583])

### 3-(3) 공식의 분자를 계산해서 sim_rating에 할당해주세요.<font color=blue>(20점)</font>

In [ ]:
sim_rating = np.matmul(df2_cosine.loc[user5_train['id'].values, :].T.values, user5_train['rating'].values)
sim_rating

array([ 1.28562007, 39.05991653, 22.01407663, ...,  1.26279642,
       13.65901885,  5.43237159])

### 3-(4) 구한 분모, 분자 값을 이용하여 평점 예측 값 pred_rating 데이터 프레임을 만들어 주세요.<font color=blue>(15점)</font> <br>(인덱스는 df2_cosine의 인덱스)

In [ ]:
pred_rating = pd.DataFrame(np.divide(sim_rating, sim_sum), index=df2_cosine.index)
pred_rating.columns=["pred"]
pred_rating

            pred
id
2       0.926045
5       3.578443
6       3.309559
11      3.763187
12      3.811819
...          ...
399106  3.393501
401387  3.304334
402672  0.968418
410921  3.014862
416437  2.239114

[8834 rows x 1 columns]

### 4. test_rate에서 유저5의 데이터를 user5_test에 할당해주세요.<font color=blue>(5점)</font>

In [ ]:
user5_test = test_rate[test_rate['userId'] == 5]
user5_test

     userId  rating     id
436       5     4.5    558
428       5     4.0    310
374       5     2.5    240
417       5     3.0    161
425       5     3.0    672
375       5     4.0  37247
411       5     3.5   8358
414       5     3.5    824
412       5     4.5   1493
388       5     3.5   9552
390       5     5.0  10144
400       5     3.5  11353
435       5     3.5   1777
363       5     4.0    771
357       5     4.0     13
448       5     4.5    496
381       5     4.0  37165
419       5     3.5   4547
432       5     4.0    508
393       5     3.5   9487
355       5     4.5  10510

### 5. user5_test와 pred_rating 데이터프레임을 병합해 아래의 결과처럼 나오도록 해주세요.<font color=blue>(5점)</font>

In [ ]:
item_cf = pd.merge(user5_test, pred_rating.loc[user5_test['id']], left_on = 'id', right_index=True)[['id', 'rating', 'pred']]
item_cf.head()

      id  rating      pred
436  558     4.5  3.807301
428  310     4.0  3.784333
374  240     2.5  3.700531
417  161     3.0  3.809754
425  672     3.0  3.794419

### 6. 앞에서 만들었던 평가지표 함수를 사용하여 rmse, mae 결과를 출력하세요.<font color=blue>(5점)</font>

In [ ]:
evaluation(item_cf['pred'], item_cf['rating'])

RMSE: 0.588
MAE: 0.486

### 7. similar movie 함수를 이용하여 Avatar와 2번째로 유사한 영화 제목과 예상 평점을 마크다운으로 작성해주세요.<font color=blue>(5점)</font><br>(유사도는 cos_matirx_2 사용)

In [ ]:
similar_movie('Avatar', cos_matrix_2)

                                           유사한 영화 TOP10      예상평점
8128                                The Kings of Summer  3.284065
8587                                           The Loft  3.321532
7497  The Chronicles of Narnia: The Voyage of the Da...  2.842588
7072                                    The Hurt Locker  3.645068
7752                                     Violet & Daisy  3.321532
4925                                        Naked Lunch  3.376687
1714                          The Man Who Knew Too Much  3.597158
4256                                    Far from Heaven  3.589522
8244                    The Hunger Games: Catching Fire  3.435007

The Loft, 3.321532